-- D&D Campaign Manager - Seed Data Export
-- Generated at: 2026-04-08T15:08:53.631Z
-- WARNING: This file uses ON CONFLICT (id) DO NOTHING. It is designed for
-- restoring into a clean database. Partial restores into an existing database
-- may fail if parent records (campaigns) are missing.

SET standard_conforming_strings = ON;

BEGIN;

-- campaigns
INSERT INTO campaigns (id, name, description, setting, status, image_url, dm_notes, created_at, updated_at) VALUES ('550e8400-e29b-41d4-a716-446655440000', 'The Accidental Vanguard', 'A bumbling apprentice wizard named Bumblethorne meant to summon legendary heroes to save his world. He got three kids from another world instead. Now they are stuck — the only way home is to help him finish what an ancient council of wizards abandoned centuries ago: collecting six powerful Fragments of the Weave scattered across six dangerous regions of an unfamiliar world. Armed with a silver compass that points not north but toward the next Fragment, three unlikely heroes must cross mountains, deserts, forests, and worse — while their well-meaning but occasionally catastrophic guide slowly grows into the wizard he always claimed to be.', 'Veranthos (D&D 5e)', 'planning', NULL, NULL, '2026-04-08T14:50:38.594982+00:00', '2026-04-08T14:50:38.594982+00:00') ON CONFLICT (id) DO NOTHING;

-- characters
INSERT INTO characters (id, campaign_id, name, character_type, player_name, race, class, subclass, level, background, alignment, hit_points_max, armor_class, speed, proficiency_bonus, notes, personality_traits, ideals, bonds, flaws, appearance, backstory, portrait_url, is_active, status, gender, size, created_at, updated_at) VALUES ('6e52661f-d630-4242-8dbb-539f12060fa5', '550e8400-e29b-41d4-a716-446655440000', 'Seraphina Thorngage', 'npc', NULL, 'halfling-stout', 'paladin', NULL, 1, 'Gutsy Striver', 'lg', 12, 10, 25, 2, NULL, 'She carries herself like she''s six feet tall and has the battle scars to prove it — and somehow, in the moment, people believe her. The swagger is real; only the physical evidence is missing.

After every chaotic fight she walks away from, she goes quiet for just a moment — looks at her hands, looks around at the carnage, shakes her head slowly, and says something under her breath like "...how am I not dead right now." Then she straightens up and acts like it never happened.', 'Justice from the Bottom Up. The strong don''t get to decide who matters. Rules and titles and institutions are all fine until the moment they start protecting the wrong people — and she has zero patience for that moment. She doesn''t need a mandate from a god or an order to know that a bully deserves to be knocked flat. The gods, she figures, can sort out the paperwork later.', 'Her mentor, Aldric. A retired soldier — scarred, skeptical, and deeply uninterested in taking on another student when she found him. She talked him into it anyway. He trained her harder than anyone else precisely because he expected her to quit, and when she didn''t, he quietly revised his opinion of both her and himself. He gave her the longsword — it was his, once. Too heavy for her to wield properly. She wields it anyway.

Home, at arm''s length. She left her halfling community voluntarily, warmly, and with a lot of firm hugs. She loves them. She is not ready to go back. There''s something she needs to prove first — not to them, to herself — and she hasn''t proved it yet. She writes when she can.', 'She cannot walk past it. A merchant berating a dockworker, a guard shaking down a child, a nobleman sneering at a servant — she will stop, she will intervene, and she will not calculate the odds first. She has started a remarkable number of fights this way. She has, inexplicably, survived all of them.

She also has a slight and persistent blind spot about her own physical limitations. Her first plan in any situation tends to assume capabilities she doesn''t quite have. Her second plan, improvised on the fly when the first plan meets reality, is usually better anyway.', 'Seraphina is stout even by halfling standards — broad-shouldered, solid, built like someone who''s been climbing hills her whole life and found them insufficient. She wears studded leather that''s been mended in four places and cleaned in all of them. The longsword across her back is genuinely too large for her frame, which she is aware of and unbothered by.

Her eyes are the first thing people notice: direct, assessing, and faintly amused — like she''s already spotted the thing in the room that''s about to go sideways and is deciding whether to stop it or let it play out. She keeps her dark hair short and practical. She smells faintly of whatever she last grabbed as an improvised weapon, which is occasionally furniture polish.', 'The Gutsy Striver grew up somewhere lovely, safe, and small — and left it voluntarily, on an ordinary morning, because she looked at the road out of town and decided she needed to know where it went. No tragedy. No catalyst. Just a halfling who woke up one day and understood that comfort and contentment aren''t the same thing.

She tried a knightly order first, drawn by the idea of doing something meaningful with the restlessness. The politics drove her out within a season — too much energy spent managing who sat at which table, not nearly enough spent on actually helping anyone. A temple came next; same problem, fancier robes. Institutions, she concluded, were designed for people who wanted to belong to something. She wanted to do something. She found Aldric living outside a market town, retired from the world and apparently committed to staying that way, and refused to leave until he agreed to train her. He made it hard on purpose, expecting her to quit. She didn''t.

What she can''t entirely explain is the luck. She''s been in situations that should have ended her — badly outnumbered, outmatched, occasionally on fire — and somehow they didn''t. She walks away, checks herself for damage that isn''t there, and genuinely cannot account for it. She doesn''t think she''s blessed, exactly. But something is either watching out for her, or the universe keeps miscounting, and she has learned not to examine it too hard in case examining it makes it stop.', NULL, TRUE, 'ready', 'female', 'small', '2026-03-24T17:23:47.256096+00:00', '2026-03-24T18:00:54.640906+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO characters (id, campaign_id, name, character_type, player_name, race, class, subclass, level, background, alignment, hit_points_max, armor_class, speed, proficiency_bonus, notes, personality_traits, ideals, bonds, flaws, appearance, backstory, portrait_url, is_active, status, gender, size, created_at, updated_at) VALUES ('550e8400-e29b-41d4-a716-446655440005', '550e8400-e29b-41d4-a716-446655440000', 'Sebastian', 'pc', 'Sebastian', 'human', 'fighter', NULL, 1, 'folkhero', 'ng', 12, 16, 30, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE, 'draft', 'male', 'medium', '2026-04-08T14:50:38.594982+00:00', '2026-04-08T14:50:38.594982+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO characters (id, campaign_id, name, character_type, player_name, race, class, subclass, level, background, alignment, hit_points_max, armor_class, speed, proficiency_bonus, notes, personality_traits, ideals, bonds, flaws, appearance, backstory, portrait_url, is_active, status, gender, size, created_at, updated_at) VALUES ('07525810-fe4a-424a-9f44-466e6fc4da16', '550e8400-e29b-41d4-a716-446655440000', 'Torbin Craghold', 'npc', '', 'dwarf-mountain', 'fighter', NULL, 1, 'soldier', 'ln', 12, 11, NULL, 2, NULL, 'Speaks in short sentences. Wastes nothing, including words.
Demonstrates rather than explains. If you want to learn, watch him first.', 'Discipline is the difference between a soldier and a corpse.', 'His old unit was wiped out on a campaign he survived by luck. He trains others so someone is ready when luck runs out again.', 'Holds beginners to a standard they can''t possibly meet yet, then acts surprised when they fail.', 'Broad even by dwarf standards, with a shaved head and a close-cropped iron-gray beard. A wide scar runs from his left jaw to his collarbone. Always in half-plate, even when he doesn''t need to be.', 'Torbin spent thirty years in the mountain garrison forces, rising to sergeant before a disastrous campaign left him the only survivor of his unit. He doesn''t talk about what happened. He retired to the lowlands, took work as a caravan guard, and eventually found himself training recruits for a small town militia — not because anyone asked him to, but because watching untrained people get hurt bothered him more than the work did. He is not warm. He is effective. For Sebastian, he''ll be the first adult who takes his instinct for combat seriously rather than trying to redirect it.', NULL, TRUE, 'ready', 'male', 'medium', '2026-04-08T15:03:09.190565+00:00', '2026-04-08T15:07:28.035081+00:00') ON CONFLICT (id) DO NOTHING;

-- sessions
INSERT INTO sessions (id, campaign_id, session_number, title, date, summary, notes, experience_awarded, loot, created_at, updated_at) VALUES ('550e8400-e29b-41d4-a716-446655440010', '550e8400-e29b-41d4-a716-446655440000', 1, 'Ambush on the Sword Coast', '2026-03-11', 'The party was ambushed by goblins while traveling along the Sword Coast. They defeated the goblin ambush party and rescued a dwarf named Gunther who was being held captive. They learned from him that Gundren Rockseeker and his partner Sildar were captured by Grol the Destroyer.', 'The party showed excellent teamwork in the first combat. Braxus'' display of combat skill was impressive. Silvara''s spell selection was strategic. The goblin ambush was just the beginning - the party will need to investigate further to find Gundren.', 150, '[]'::jsonb, '2026-04-08T14:50:38.594982+00:00', '2026-04-08T14:50:38.594982+00:00') ON CONFLICT (id) DO NOTHING;

-- encounters
INSERT INTO encounters (id, session_id, campaign_id, name, description, status, round, combatants, notes, created_at, updated_at) VALUES ('550e8400-e29b-41d4-a716-446655440020', '550e8400-e29b-41d4-a716-446655440010', '550e8400-e29b-41d4-a716-446655440000', 'Goblin Ambush', 'The party was ambushed by a gang of goblins on the Sword Coast road.', 'completed', 3, '[{"ac":16,"name":"Braxus Ironforge","hp_max":12,"is_player":true,"conditions":[],"hp_current":12,"initiative":11,"character_id":null},{"ac":12,"name":"Silvara Moonwhisper","hp_max":6,"is_player":true,"conditions":[],"hp_current":6,"initiative":14,"character_id":null},{"ac":15,"name":"Goblin Warrior 1","hp_max":7,"is_player":false,"conditions":["unconscious"],"hp_current":0,"initiative":9,"character_id":null},{"ac":15,"name":"Goblin Warrior 2","hp_max":7,"is_player":false,"conditions":["unconscious"],"hp_current":0,"initiative":8,"character_id":null},{"ac":17,"name":"Grol the Destroyer","hp_max":22,"is_player":false,"conditions":["frightened"],"hp_current":5,"initiative":10,"character_id":null}]'::jsonb, 'Grol fled combat after being surrounded. The party successfully defeated the goblin war party.', '2026-04-08T14:50:38.594982+00:00', '2026-04-08T14:50:38.594982+00:00') ON CONFLICT (id) DO NOTHING;

-- notes
INSERT INTO notes (id, campaign_id, title, content, category, tags, is_pinned, created_at, updated_at) VALUES ('550e8400-e29b-41d4-a716-446655440030', '550e8400-e29b-41d4-a716-446655440000', 'Main Quest: Find Gundren Rockseeker', 'Gundren was captured by goblins led by Grol the Destroyer. The goblins were hired by the Black Spider to prevent Gundren from opening the Lost Mine of Phandelver. The party must find the goblin hideout (Cragmaw Castle) and rescue Gundren.', 'quest', ARRAY['main_quest', 'gundren', 'priority']::text[], TRUE, '2026-04-08T14:50:38.594982+00:00', '2026-04-08T14:50:38.594982+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO notes (id, campaign_id, title, content, category, tags, is_pinned, created_at, updated_at) VALUES ('550e8400-e29b-41d4-a716-446655440031', '550e8400-e29b-41d4-a716-446655440000', 'Phandalin Town Hook', 'Phandalin is a sleepy frontier town that serves as a base for adventurers. Sildar Hallwinter has connections here. The town is threatened by a gang of ruffians called the Redbrand Mercenaries who are bullying the townsfolk.', 'location', ARRAY['phandalin', 'town', 'redbrand']::text[], FALSE, '2026-04-08T14:50:38.594982+00:00', '2026-04-08T14:50:38.594982+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO notes (id, campaign_id, title, content, category, tags, is_pinned, created_at, updated_at) VALUES ('550e8400-e29b-41d4-a716-446655440032', '550e8400-e29b-41d4-a716-446655440000', 'NPC: Sildar Hallwinter', 'A former adventurer and mercenary in his 50s. Missing his left arm from a goblin attack. Friendly to the party and can provide information about Gundren and the mines. Uses Sildar as a source of quests and information.', 'npc', ARRAY['ally', 'merchant', 'quest_giver']::text[], FALSE, '2026-04-08T14:50:38.594982+00:00', '2026-04-08T14:50:38.594982+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO notes (id, campaign_id, title, content, category, tags, is_pinned, created_at, updated_at) VALUES ('550e8400-e29b-41d4-a716-446655440033', '550e8400-e29b-41d4-a716-446655440000', 'Villain: The Black Spider', 'A mysterious wizard who hired the goblins to capture Gundren. Wants to keep the Lost Mine of Phandelver secret. Likely operating from a stronghold somewhere in the region. Identity and motives remain unknown.', 'npc', ARRAY['villain', 'enemy', 'mysterious']::text[], FALSE, '2026-04-08T14:50:38.594982+00:00', '2026-04-08T14:50:38.594982+00:00') ON CONFLICT (id) DO NOTHING;
INSERT INTO notes (id, campaign_id, title, content, category, tags, is_pinned, created_at, updated_at) VALUES ('550e8400-e29b-41d4-a716-446655440034', '550e8400-e29b-41d4-a716-446655440000', 'Lore: The Lost Mine of Phandelver', 'An ancient dwarven mine that produced exquisite mithril. It was lost centuries ago and its location has been forgotten. Recent discoveries suggest it may be rediscoverable. The mine contains vast wealth and powerful magical artifacts.', 'lore', ARRAY['magic', 'dwarves', 'treasure']::text[], FALSE, '2026-04-08T14:50:38.594982+00:00', '2026-04-08T14:50:38.594982+00:00') ON CONFLICT (id) DO NOTHING;

-- character_build_levels
INSERT INTO character_build_levels (character_id, sequence, base_abilities, ability_method, choices) VALUES ('550e8400-e29b-41d4-a716-446655440005', 0, '{"str": 15, "dex": 12, "con": 14, "int": 8, "wis": 10, "cha": 13}'::jsonb, 'standard-array', '{"language-choice:race:human:0": {"type": "language-choice", "languages": ["giant"]}}'::jsonb) ON CONFLICT (character_id, sequence) DO NOTHING;
INSERT INTO character_build_levels (character_id, sequence, class_id, class_level, hp_roll, choices) VALUES ('550e8400-e29b-41d4-a716-446655440005', 1, 'fighter', 1, null, '{"skill-choice:class:fighter:0": {"type": "skill-choice", "skills": ["animalhandling", "survival"]}}'::jsonb) ON CONFLICT (character_id, sequence) DO NOTHING;

COMMIT;
