import { describe, it, expect } from 'vitest';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  computeCoverageMatrix,
  renderCoverageMarkdown,
  hasL19EpicBoonGrant,
  type ForkCoverage,
} from '@/lib/sources/coverage-matrix';
import { createChoiceKey } from '@/types/choices';
import type { LevelUp } from '@/types/sources';

/**
 * Coverage gate for the 2024 PHB source data.
 *
 * Two jobs:
 *   1. Hard invariants that must never break (every canonical option has a source).
 *   2. Regression ratchets: structural-complete counts must not drop below the
 *      recorded baseline. When you intentionally improve coverage, bump the
 *      baseline here — that is the deliberate, reviewable record of progress.
 *
 * The committed report at `docs/coverage-matrix.md` is regenerated by
 * `npm run coverage:matrix`; this suite fails if it drifts out of date.
 */

const DOC_PATH = resolve(process.cwd(), 'docs/coverage-matrix.md');

// Regression ratchet — minimum structurally-complete entries per fork. Bump these
// upward as RAW implementation lands; never lower them to make a regression pass.
const COMPLETE_BASELINE = {
  classes: 10,
  subclasses: 3,
  species: 10,
  backgrounds: 16,
} as const;

const matrix = computeCoverageMatrix();
const forks: Record<keyof typeof COMPLETE_BASELINE, ForkCoverage> = {
  classes: matrix.classes,
  subclasses: matrix.subclasses,
  species: matrix.species,
  backgrounds: matrix.backgrounds,
};

describe('2024 PHB coverage matrix', () => {
  describe('hard invariants', () => {
    it.each(Object.keys(forks) as (keyof typeof forks)[])('every canonical %s option has a source entry', (fork) => {
      const missing = forks[fork].entries.filter((e) => e.status === 'missing').map((e) => e.id);
      expect(missing, `${fork} missing sources: ${missing.join(', ')}`).toEqual([]);
    });

    it.each(Object.keys(forks) as (keyof typeof forks)[])('%s status counts sum to the total', (fork) => {
      const { counts, total } = forks[fork];
      expect(counts.missing + counts.stub + counts.partial + counts.complete).toBe(total);
    });
  });

  describe('regression ratchet (structural completeness must not regress)', () => {
    it.each(Object.entries(COMPLETE_BASELINE) as [keyof typeof forks, number][])(
      '%s has at least %d structurally-complete entries',
      (fork, baseline) => {
        expect(
          forks[fork].counts.complete,
          `${fork} complete dropped below baseline — fix the regression or, if intentional, lower the baseline deliberately`
        ).toBeGreaterThanOrEqual(baseline);
      }
    );
  });

  describe('committed report is current', () => {
    it('docs/coverage-matrix.md matches the generated matrix', () => {
      const rendered = renderCoverageMarkdown(matrix);
      if (process.env.COVERAGE_WRITE) {
        writeFileSync(DOC_PATH, rendered, 'utf8');
        return;
      }
      let committed: string;
      try {
        committed = readFileSync(DOC_PATH, 'utf8');
      } catch {
        throw new Error('docs/coverage-matrix.md is missing — run `npm run coverage:matrix`');
      }
      expect(committed, 'docs/coverage-matrix.md is stale — run `npm run coverage:matrix`').toBe(rendered);
    });
  });
});

describe('hasL19EpicBoonGrant', () => {
  // Synthetic level array: 18 empty levels (indices 0-17) followed by the level-19 slot
  // (index 18) under test — computeClassCoverage isn't parameterizable with a synthetic
  // ClassSource, so this exercises the extracted detector directly against a minimal
  // LevelUp array instead of the full CLASS_SOURCES data.
  function levelsWithL19(l19Grants: LevelUp['grants']): readonly LevelUp[] {
    const emptyLevels: LevelUp[] = Array.from({ length: 18 }, () => ({ grants: [] }));
    return [...emptyLevels, { grants: l19Grants }];
  }

  it('returns false when level 19 has only an ASI grant', () => {
    const levels = levelsWithL19([
      { type: 'asi', key: createChoiceKey('asi', 'class', 'cleric', 4), points: 2, from: null },
    ]);
    expect(hasL19EpicBoonGrant(levels)).toBe(false);
  });

  it('returns false when level 19 has a feat-choice grant with category "general"', () => {
    const levels = levelsWithL19([
      { type: 'feat-choice', key: createChoiceKey('feat-choice', 'class', 'cleric', 4), from: null, category: 'general' },
    ]);
    expect(hasL19EpicBoonGrant(levels)).toBe(false);
  });

  it('returns false when level 19 has no grants', () => {
    expect(hasL19EpicBoonGrant(levelsWithL19([]))).toBe(false);
  });

  it('returns true when level 19 has a solo feat-choice grant with category "epicBoon"', () => {
    const levels = levelsWithL19([
      { type: 'feat-choice', key: createChoiceKey('feat-choice', 'class', 'cleric', 4), from: null, category: 'epicBoon' },
    ]);
    expect(hasL19EpicBoonGrant(levels)).toBe(true);
  });
});
