import type { ClassId } from '@/lib/dnd-helpers';
import type { SpellDef } from '@/types/spells';

export const SPELL_CATALOG = [
  {
    id: 'druidcraft',
    level: 0,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['druid'],
  },
  {
    id: 'guidance',
    level: 0,
    school: 'divination',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 minute',
    nativeClasses: ['cleric', 'druid'],
  },
  {
    id: 'mending',
    level: 0,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 minute',
    range: 'Touch',
    components: {
      verbal: true,
      somatic: true,
      material: 'two lodestones',
    },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'cleric', 'druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'message',
    level: 0,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a copper wire' },
    duration: '1 round',
    nativeClasses: ['bard', 'druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'poison-spray',
    level: 0,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['druid', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'produce-flame',
    level: 0,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: '10 minutes',
    nativeClasses: ['druid'],
  },
  {
    id: 'resistance',
    level: 0,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a miniature cloak' },
    duration: '1 minute',
    nativeClasses: ['cleric', 'druid'],
  },
  {
    id: 'shillelagh',
    level: 0,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'mistletoe and shamrock leaves, plus a club or quarterstaff' },
    duration: '1 minute',
    nativeClasses: ['druid'],
  },
  {
    id: 'spare-the-dying',
    level: 0,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '15 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['cleric', 'druid'],
  },
  {
    id: 'thorn-whip',
    level: 0,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'the stem of a plant with thorns' },
    duration: 'Instantaneous',
    nativeClasses: ['druid'],
  },
  {
    id: 'speak-with-animals',
    level: 1,
    school: 'divination',
    ritual: true,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: '10 minutes',
    nativeClasses: ['bard', 'druid', 'ranger'],
  },
  {
    id: 'commune-with-nature',
    level: 5,
    school: 'divination',
    ritual: true,
    concentration: false,
    castingTime: '1 minute',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['druid', 'ranger'],
  },
  // ── Cleric domain spells (added for issue #142) ──────────────────────────
  // Light cantrip — Light Domain bonus cantrip (cleric, bard, sorcerer, wizard in 2024)
  {
    id: 'light',
    level: 0,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: false, material: 'a firefly or phosphorescent moss' },
    duration: '1 hour',
    nativeClasses: ['bard', 'cleric', 'sorcerer', 'wizard'],
  },
  // Life Domain L3
  {
    id: 'aid',
    level: 2,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a tiny strip of white cloth' },
    duration: '8 hours',
    nativeClasses: ['cleric', 'paladin', 'ranger'],
  },
  {
    id: 'bless',
    level: 1,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a sprinkle of holy water' },
    duration: 'Up to 1 minute',
    nativeClasses: ['cleric', 'paladin'],
  },
  {
    id: 'cure-wounds',
    level: 1,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'cleric', 'druid', 'paladin', 'ranger'],
  },
  {
    id: 'lesser-restoration',
    level: 2,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Bonus Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'cleric', 'druid', 'paladin', 'ranger'],
  },
  // Life Domain L5
  {
    id: 'mass-healing-word',
    level: 3,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Bonus Action',
    range: '60 feet',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'cleric'],
  },
  {
    id: 'revivify',
    level: 3,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'a diamond worth 300+ GP, which the spell consumes' },
    duration: 'Instantaneous',
    nativeClasses: ['cleric', 'druid', 'paladin', 'ranger'],
  },
  // Life Domain L7
  {
    id: 'aura-of-life',
    level: 4,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self (30-foot emanation)',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 10 minutes',
    nativeClasses: ['cleric', 'paladin'],
  },
  {
    id: 'death-ward',
    level: 4,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: '8 hours',
    nativeClasses: ['cleric', 'paladin'],
  },
  // Life Domain L9
  {
    id: 'greater-restoration',
    level: 5,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'diamond dust worth 100+ GP, which the spell consumes' },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'cleric', 'druid'],
  },
  {
    id: 'mass-cure-wounds',
    level: 5,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'cleric', 'druid'],
  },
  // Light Domain L3
  {
    id: 'burning-hands',
    level: 1,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self (15-foot cone)',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'faerie-fire',
    level: 1,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['bard', 'druid'],
  },
  {
    id: 'scorching-ray',
    level: 2,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  {
    id: 'see-invisibility',
    level: 2,
    school: 'divination',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a pinch of talc and a small sprinkling of powdered silver' },
    duration: '1 hour',
    nativeClasses: ['bard', 'sorcerer', 'wizard'],
  },
  // Light Domain L5
  {
    id: 'daylight',
    level: 3,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 hour',
    nativeClasses: ['cleric', 'druid', 'ranger', 'sorcerer'],
  },
  {
    id: 'fireball',
    level: 3,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: 'a tiny ball of bat guano and sulfur' },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  // Light Domain L7
  {
    id: 'arcane-eye',
    level: 4,
    school: 'divination',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a bit of bat fur' },
    duration: 'Up to 1 hour',
    nativeClasses: ['wizard'],
  },
  {
    id: 'wall-of-fire',
    level: 4,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a small piece of phosphorus' },
    duration: 'Up to 1 minute',
    nativeClasses: ['druid', 'sorcerer', 'wizard'],
  },
  // Light Domain L9
  {
    id: 'flame-strike',
    level: 5,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'pinch of sulfur' },
    duration: 'Instantaneous',
    nativeClasses: ['cleric'],
  },
  {
    id: 'scrying',
    level: 5,
    school: 'divination',
    ritual: false,
    concentration: true,
    castingTime: '10 minutes',
    range: 'Self',
    components: {
      verbal: true,
      somatic: true,
      material: 'a focus worth 1,000+ GP, such as a crystal ball, a silver mirror, or a font filled with holy water',
    },
    duration: 'Up to 10 minutes',
    nativeClasses: ['bard', 'cleric', 'druid', 'warlock', 'wizard'],
  },
  // Trickery Domain L3
  {
    id: 'charm-person',
    level: 1,
    school: 'enchantment',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 hour',
    nativeClasses: ['bard', 'druid', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'disguise-self',
    level: 1,
    school: 'illusion',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 hour',
    nativeClasses: ['bard', 'sorcerer', 'wizard'],
  },
  {
    id: 'invisibility',
    level: 2,
    school: 'illusion',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'an eyelash encased in gum arabic' },
    duration: 'Up to 1 hour',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'pass-without-trace',
    level: 2,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: {
      verbal: false,
      somatic: true,
      material: 'ashes from a burned leaf of mistletoe and a sprig of spruce',
    },
    duration: 'Up to 1 hour',
    nativeClasses: ['druid', 'ranger'],
  },
  // Trickery Domain L5
  {
    id: 'hypnotic-pattern',
    level: 3,
    school: 'illusion',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: {
      verbal: false,
      somatic: true,
      material: 'a glowing stick of incense or a crystal vial filled with phosphorescent material',
    },
    duration: 'Up to 1 minute',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'nondetection',
    level: 3,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: {
      verbal: true,
      somatic: true,
      material: 'a pinch of diamond dust worth 25+ GP, which the spell consumes',
    },
    duration: '8 hours',
    nativeClasses: ['bard', 'ranger', 'wizard'],
  },
  // Trickery Domain L7
  {
    id: 'confusion',
    level: 4,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'three nut shells' },
    duration: 'Up to 1 minute',
    nativeClasses: ['bard', 'druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'dimension-door',
    level: 4,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '500 feet',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  // Trickery Domain L9
  {
    id: 'dominate-person',
    level: 5,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['bard', 'sorcerer', 'wizard'],
  },
  {
    id: 'modify-memory',
    level: 5,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: false, somatic: true, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['bard', 'wizard'],
  },
  // War Domain L3
  {
    id: 'guiding-bolt',
    level: 1,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 round',
    nativeClasses: ['cleric'],
  },
  {
    // 2024 PHB: Magic Weapon — no longer concentration, duration 1 hour
    id: 'magic-weapon',
    level: 2,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Bonus Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 hour',
    nativeClasses: ['paladin', 'ranger', 'wizard'],
  },
  {
    id: 'shield-of-faith',
    level: 1,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a small parchment with a bit of holy text on it' },
    duration: 'Up to 10 minutes',
    nativeClasses: ['cleric', 'paladin'],
  },
  {
    // 2024 PHB: Spiritual Weapon — no longer concentration, uses Bonus Action to summon and attack
    id: 'spiritual-weapon',
    level: 2,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Bonus Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '1 minute',
    nativeClasses: ['cleric'],
  },
  // War Domain L5
  {
    id: 'crusaders-mantle',
    level: 3,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self (30-foot emanation)',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['paladin'],
  },
  {
    id: 'spirit-guardians',
    level: 3,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self (15-foot emanation)',
    components: { verbal: true, somatic: true, material: 'a holy symbol' },
    duration: 'Up to 10 minutes',
    nativeClasses: ['cleric'],
  },
  // War Domain L7
  {
    id: 'fire-shield',
    level: 4,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a bit of phosphorus or a firefly' },
    duration: '10 minutes',
    nativeClasses: ['wizard'],
  },
  {
    id: 'freedom-of-movement',
    level: 4,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: {
      verbal: true,
      somatic: true,
      material: 'a leather strap, bound around the arm or a similar appendage',
    },
    duration: '1 hour',
    nativeClasses: ['bard', 'cleric', 'druid', 'ranger'],
  },
  // War Domain L9
  {
    id: 'hold-monster',
    level: 5,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'a small, straight piece of iron' },
    duration: 'Up to 1 minute',
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'steel-wind-strike',
    level: 5,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: false, somatic: true, material: 'a melee weapon worth at least 1 SP' },
    duration: 'Instantaneous',
    nativeClasses: ['ranger', 'wizard'],
  },
  // Circle of the Land — Arid cantrip
  {
    id: 'fire-bolt',
    level: 0,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  // Circle of the Land — Arid L2
  {
    id: 'blur',
    level: 2,
    school: 'illusion',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  // Circle of the Land — Arid L7 (Druid level 7 → spell level 4)
  {
    id: 'blight',
    level: 4,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['druid', 'sorcerer', 'warlock', 'wizard'],
  },
  // Circle of the Land — Arid L9 (Druid level 9 → spell level 5)
  {
    id: 'wall-of-stone',
    level: 5,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: 'a small block of granite' },
    duration: 'Up to 10 minutes',
    nativeClasses: ['druid', 'sorcerer', 'wizard'],
  },
  // Circle of the Land — Polar cantrip
  {
    id: 'ray-of-frost',
    level: 0,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  // Circle of the Land — Polar L3 (Druid level 3 → spell level 1)
  {
    id: 'fog-cloud',
    level: 1,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 hour',
    nativeClasses: ['druid', 'ranger', 'sorcerer', 'wizard'],
  },
  // Circle of the Land — Polar L3 (Druid level 3 → spell level 2)
  {
    id: 'hold-person',
    level: 2,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a small, straight piece of iron' },
    duration: 'Up to 1 minute',
    nativeClasses: ['bard', 'cleric', 'druid', 'sorcerer', 'warlock', 'wizard'],
  },
  // Circle of the Land — Polar L5 (Druid level 5 → spell level 3)
  {
    id: 'sleet-storm',
    level: 3,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of dust and a few drops of water' },
    duration: 'Up to 1 minute',
    nativeClasses: ['druid', 'sorcerer', 'wizard'],
  },
  // Circle of the Land — Polar L7 (Druid level 7 → spell level 4)
  {
    id: 'ice-storm',
    level: 4,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '300 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of dust and a few drops of water' },
    duration: 'Instantaneous',
    nativeClasses: ['druid', 'sorcerer', 'wizard'],
  },
  // Circle of the Land — Polar L9 (Druid level 9 → spell level 5)
  {
    id: 'cone-of-cold',
    level: 5,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self (60-foot cone)',
    components: { verbal: true, somatic: true, material: 'a small crystal or glass cone' },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  // Circle of the Land — Temperate cantrip
  {
    id: 'shocking-grasp',
    level: 0,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  // Circle of the Land — Temperate L3 (Druid level 3 → spell level 1)
  {
    id: 'sleep',
    level: 1,
    school: 'enchantment',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a pinch of sand, rose petals, or a cricket' },
    duration: '1 minute',
    nativeClasses: ['bard', 'sorcerer', 'wizard'],
  },
  // Circle of the Land — Temperate L3 (Druid level 3 → spell level 2)
  {
    id: 'misty-step',
    level: 2,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'warlock', 'wizard'],
  },
  // Circle of the Land — Temperate L5 (Druid level 5 → spell level 3)
  {
    id: 'lightning-bolt',
    level: 3,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Self (100-foot line)',
    components: { verbal: true, somatic: true, material: 'a bit of fur and a rod of amber, crystal, or glass' },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  // Circle of the Land — Temperate L9 (Druid level 9 → spell level 5)
  {
    id: 'tree-stride',
    level: 5,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['druid', 'ranger'],
  },
  // Circle of the Land — Tropical cantrip
  {
    id: 'acid-splash',
    level: 0,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  // Circle of the Land — Tropical L3 (Druid level 3 → spell level 1)
  {
    id: 'ray-of-sickness',
    level: 1,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  // Circle of the Land — Tropical L3 (Druid level 3 → spell level 2)
  {
    id: 'web',
    level: 2,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a bit of spiderweb' },
    duration: 'Up to 1 hour',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  // Circle of the Land — Tropical L5 (Druid level 5 → spell level 3)
  {
    id: 'stinking-cloud',
    level: 3,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'a rotten egg or several skunk cabbage leaves' },
    duration: 'Up to 1 minute',
    nativeClasses: ['bard', 'sorcerer', 'wizard'],
  },
  // Circle of the Land — Tropical L7 (Druid level 7 → spell level 4)
  {
    id: 'polymorph',
    level: 4,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: 'a caterpillar cocoon' },
    duration: 'Up to 1 hour',
    nativeClasses: ['bard', 'druid', 'sorcerer', 'wizard'],
  },
  // Circle of the Land — Tropical L9 (Druid level 9 → spell level 5)
  {
    id: 'insect-plague',
    level: 5,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '300 feet',
    components: {
      verbal: true,
      somatic: true,
      material: 'a few grains of sugar, some kernels of grain, and a smear of fat',
    },
    duration: 'Up to 10 minutes',
    nativeClasses: ['cleric', 'druid', 'ranger', 'sorcerer'],
  },
  // ── Paladin oath spells (added for issue #150) ────────────────────────────
  // Devotion L3
  {
    id: 'protection-from-evil-and-good',
    level: 1,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: {
      verbal: true,
      somatic: true,
      material: 'holy water or powdered silver and iron, which the spell consumes',
    },
    duration: '10 minutes',
    // 2024 PHB: native to cleric, druid, paladin, warlock, wizard
    nativeClasses: ['cleric', 'druid', 'paladin', 'warlock', 'wizard'],
  },
  // Devotion/Glory L5
  {
    id: 'zone-of-truth',
    level: 2,
    school: 'enchantment',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '60 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '10 minutes',
    // 2024 PHB: native to cleric, paladin
    nativeClasses: ['cleric', 'paladin'],
  },
  // Devotion L9
  {
    // 2024 PHB: Beacon of Hope — school is Abjuration (same as 2014)
    // FLAG: school should be verified against 2024 PHB — confident it is Abjuration, not Evocation
    id: 'beacon-of-hope',
    level: 3,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 minute',
    // 2024 PHB: native to cleric
    nativeClasses: ['cleric'],
  },
  {
    id: 'dispel-magic',
    level: 3,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '120 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    // 2024 PHB: native to bard, cleric, druid, paladin, sorcerer, warlock, wizard
    nativeClasses: ['bard', 'cleric', 'druid', 'paladin', 'sorcerer', 'warlock', 'wizard'],
  },
  // Devotion L13
  {
    id: 'guardian-of-faith',
    level: 4,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: false, material: false },
    duration: '8 hours',
    // 2024 PHB: native to cleric only (oath-granted to Devotion Paladins but not on the native Paladin list)
    nativeClasses: ['cleric'],
  },
  // Devotion/Ancients L17
  {
    id: 'commune',
    level: 5,
    school: 'divination',
    ritual: true,
    concentration: false,
    castingTime: '1 minute',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'incense and a vial of holy or unholy water' },
    duration: '1 minute',
    // 2024 PHB: native to cleric only (oath-granted to Devotion Paladins but not on the native Paladin list)
    nativeClasses: ['cleric'],
  },
  // Glory L3
  {
    id: 'heroism',
    level: 1,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 minute',
    // 2024 PHB: native to bard, paladin
    nativeClasses: ['bard', 'paladin'],
  },
  // Glory L5
  {
    id: 'enhance-ability',
    level: 2,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Touch',
    components: {
      verbal: true,
      somatic: true,
      material: 'fur or a feather from a beast',
    },
    duration: 'Up to 1 hour',
    // 2024 PHB: native to bard, cleric, druid, ranger, sorcerer, warlock, wizard
    nativeClasses: ['bard', 'cleric', 'druid', 'ranger', 'sorcerer', 'warlock', 'wizard'],
  },
  // Glory/Vengeance L9
  {
    id: 'haste',
    level: 3,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'a shaving of licorice root' },
    duration: 'Up to 1 minute',
    nativeClasses: ['sorcerer', 'wizard'],
  },
  // Glory/Ancients/Vengeance L9
  {
    id: 'protection-from-energy',
    level: 3,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 hour',
    nativeClasses: ['cleric', 'druid', 'ranger', 'sorcerer', 'wizard'],
  },
  // Glory L13
  {
    id: 'compulsion',
    level: 4,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['bard'],
  },
  // Glory L17
  {
    id: 'legend-lore',
    level: 5,
    school: 'divination',
    ritual: false,
    concentration: false,
    castingTime: '10 minutes',
    range: 'Self',
    components: {
      verbal: true,
      somatic: true,
      material: 'incense worth 250+ GP, which the spell consumes, and four ivory strips worth 50+ GP each',
    },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'cleric', 'wizard'],
  },
  {
    // "Yolande's Regal Presence" — 2024-NEW spell (not in 2014 PHB).
    // Slug follows repo convention (apostrophes dropped, lowercase, hyphens).
    // 2024 PHB: native to bard and wizard (oath-granted to Glory Paladins but not on the native Paladin list).
    id: 'yolandes-regal-presence',
    level: 5,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a miniature tiara' },
    duration: 'Up to 1 minute',
    nativeClasses: ['bard', 'wizard'],
  },
  // Ancients L3
  {
    id: 'ensnaring-strike',
    level: 1,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: 'Self',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 1 minute',
    nativeClasses: ['ranger'],
  },
  // Ancients L5
  {
    id: 'moonbeam',
    level: 2,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '120 feet',
    components: {
      verbal: true,
      somatic: true,
      material: 'several seeds of any moonseed plant and a piece of opalescent feldspar',
    },
    duration: 'Up to 1 minute',
    nativeClasses: ['druid'],
  },
  // Ancients L9
  {
    id: 'plant-growth',
    level: 3,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '150 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Instantaneous',
    nativeClasses: ['bard', 'druid', 'ranger'],
  },
  // Ancients L13
  {
    id: 'stoneskin',
    level: 4,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Touch',
    components: {
      verbal: true,
      somatic: true,
      material: 'diamond dust worth 100+ GP, which the spell consumes',
    },
    duration: 'Up to 1 hour',
    nativeClasses: ['druid', 'ranger', 'sorcerer', 'wizard'],
  },
  // Vengeance L3
  {
    id: 'bane',
    level: 1,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '30 feet',
    components: {
      verbal: true,
      somatic: true,
      material: 'a drop of blood',
    },
    duration: 'Up to 1 minute',
    // 2024 PHB: native to bard, cleric, warlock
    nativeClasses: ['bard', 'cleric', 'warlock'],
  },
  {
    id: 'hunters-mark',
    level: 1,
    school: 'divination',
    ritual: false,
    concentration: true,
    castingTime: 'Bonus Action',
    range: '90 feet',
    components: { verbal: true, somatic: false, material: false },
    duration: 'Up to 1 hour',
    nativeClasses: ['ranger'],
  },
  // Vengeance L13
  {
    id: 'banishment',
    level: 4,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: 'an item distasteful to the target' },
    duration: 'Up to 1 minute',
    // 2024 PHB: native to cleric, paladin, sorcerer, warlock, wizard
    nativeClasses: ['cleric', 'paladin', 'sorcerer', 'warlock', 'wizard'],
  },
  // Fey Wanderer L3
  {
    id: 'rope-trick',
    level: 2,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: 'powdered corn extract and a twisted loop of parchment' },
    duration: '1 hour',
    // 2024 PHB: native to wizard
    nativeClasses: ['wizard'],
  },
  // Fey Wanderer L9 / Gloom Stalker L9
  {
    id: 'fear',
    level: 3,
    school: 'illusion',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: true, somatic: true, material: 'a white feather or the heart of a hen' },
    duration: 'Up to 1 minute',
    // 2024 PHB: native to bard, sorcerer, warlock, wizard
    nativeClasses: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  // Fey Wanderer L9
  {
    id: 'summon-fey',
    level: 3,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: '90 feet',
    components: { verbal: true, somatic: true, material: 'a gilded flower worth 300+ GP' },
    duration: 'Up to 1 hour',
    // 2024 PHB: native to druid, ranger, warlock, wizard
    nativeClasses: ['druid', 'ranger', 'warlock', 'wizard'],
  },
  // Gloom Stalker L13
  {
    id: 'greater-invisibility',
    level: 4,
    school: 'illusion',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Touch',
    components: { verbal: true, somatic: true, material: false },
    duration: 'Up to 1 minute',
    // 2024 PHB: native to bard, sorcerer, wizard
    nativeClasses: ['bard', 'sorcerer', 'wizard'],
  },
  // Fey Wanderer L17
  {
    id: 'mislead',
    level: 5,
    school: 'illusion',
    ritual: false,
    concentration: true,
    castingTime: 'Action',
    range: 'Self',
    components: { verbal: false, somatic: true, material: false },
    duration: 'Up to 1 hour',
    // 2024 PHB: native to bard, wizard
    nativeClasses: ['bard', 'wizard'],
  },
  // Gloom Stalker L17
  {
    id: 'seeming',
    level: 5,
    school: 'illusion',
    ritual: false,
    concentration: false,
    castingTime: 'Action',
    range: '30 feet',
    components: { verbal: true, somatic: true, material: false },
    duration: '8 hours',
    // 2024 PHB: native to bard, sorcerer, wizard
    nativeClasses: ['bard', 'sorcerer', 'wizard'],
  },
] as const satisfies readonly SpellDef[];

export type SpellId = (typeof SPELL_CATALOG)[number]['id'];

export function isSpellId(id: string): id is SpellId {
  return (SPELL_CATALOG as readonly { id: string }[]).some((s) => s.id === id);
}

export function getSpellDef(id: string): SpellDef | undefined {
  return (SPELL_CATALOG as readonly SpellDef[]).find((s) => s.id === id);
}

export function requireSpellDef(id: string): SpellDef {
  const def = getSpellDef(id);
  if (!def) {
    throw new Error(`Unknown spell id "${id}" — no entry in SPELL_CATALOG`);
  }
  return def;
}

export function getSpellsForList(classId: ClassId, level?: number): readonly SpellDef[] {
  return (SPELL_CATALOG as readonly SpellDef[]).filter(
    (s) => (s.nativeClasses as readonly string[]).includes(classId) && (level === undefined || s.level === level)
  );
}
