import type { SpellDef, SpellLevel } from '@/types/spells';
import type { ClassId } from '@/lib/dnd-helpers';
import { getLogger } from '@/lib/logger';
import type gamedata from '@/locales/en/gamedata.json';

const logger = getLogger('spells');

// ---------------------------------------------------------------------------
// Spell Catalog
// Spell names and descriptions live in gamedata.json under spells.<id>.name/description.
// Only metadata is stored here (level, school, ritual, concentration, etc.).
// ---------------------------------------------------------------------------

export const SPELL_CATALOG: readonly SpellDef[] = [
  // ---------------------------
  // Cantrips (level 0) — Druid
  // ---------------------------
  {
    id: 'druidcraft',
    level: 0,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['druid'],
  },
  {
    id: 'guidance',
    level: 0,
    school: 'divination',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Up to 1 minute',
    classes: ['cleric', 'druid'],
  },
  {
    id: 'mending',
    level: 0,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 minute',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    classes: ['bard', 'cleric', 'druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'poison-spray',
    level: 0,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: '10 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['druid', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'produce-flame',
    level: 0,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: '10 minutes',
    classes: ['druid'],
  },
  {
    id: 'resistance',
    level: 0,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 1 minute',
    classes: ['cleric', 'druid'],
  },
  {
    id: 'shillelagh',
    level: 0,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 bonus action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 minute',
    classes: ['druid'],
  },
  {
    id: 'thorn-whip',
    level: 0,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    classes: ['druid'],
  },
  // ---------------------------
  // Level 1 — Druid
  // ---------------------------
  {
    id: 'animal-friendship',
    level: 1,
    school: 'enchantment',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: '24 hours',
    classes: ['bard', 'druid', 'ranger'],
  },
  {
    id: 'charm-person',
    level: 1,
    school: 'enchantment',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: '1 hour',
    classes: ['bard', 'druid', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'create-or-destroy-water',
    level: 1,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    classes: ['cleric', 'druid'],
  },
  {
    id: 'cure-wounds',
    level: 1,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger'],
  },
  {
    id: 'detect-magic',
    level: 1,
    school: 'divination',
    ritual: true,
    concentration: true,
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 10 minutes',
    classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'sorcerer', 'wizard'],
  },
  {
    id: 'detect-poison-and-disease',
    level: 1,
    school: 'divination',
    ritual: true,
    concentration: true,
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 10 minutes',
    classes: ['cleric', 'druid', 'paladin', 'ranger'],
  },
  {
    id: 'entangle',
    level: 1,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '90 feet',
    components: 'V, S',
    duration: 'Up to 1 minute',
    classes: ['druid'],
  },
  {
    id: 'faerie-fire',
    level: 1,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '60 feet',
    components: 'V',
    duration: 'Up to 1 minute',
    classes: ['bard', 'druid'],
  },
  {
    id: 'fog-cloud',
    level: 1,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Up to 1 hour',
    classes: ['druid', 'ranger', 'sorcerer', 'wizard'],
  },
  {
    id: 'goodberry',
    level: 1,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    classes: ['druid', 'ranger'],
  },
  {
    id: 'healing-word',
    level: 1,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: '1 bonus action',
    range: '60 feet',
    components: 'V',
    duration: 'Instantaneous',
    classes: ['bard', 'cleric', 'druid'],
  },
  {
    id: 'ice-knife',
    level: 1,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: '60 feet',
    components: 'S, M',
    duration: 'Instantaneous',
    classes: ['druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'jump',
    level: 1,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 minute',
    classes: ['druid', 'ranger', 'sorcerer', 'wizard'],
  },
  {
    id: 'longstrider',
    level: 1,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 hour',
    classes: ['bard', 'druid', 'ranger', 'wizard'],
  },
  {
    id: 'purify-food-and-drink',
    level: 1,
    school: 'transmutation',
    ritual: true,
    concentration: false,
    castingTime: '1 action',
    range: '10 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['cleric', 'druid', 'paladin'],
  },
  {
    id: 'speak-with-animals',
    level: 1,
    school: 'divination',
    ritual: true,
    concentration: false,
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: '10 minutes',
    classes: ['bard', 'druid', 'ranger'],
  },
  {
    id: 'thunderwave',
    level: 1,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: 'Self (15-foot cube)',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['bard', 'cleric', 'druid', 'sorcerer', 'wizard'],
  },
  // ---------------------------
  // Level 2 — Druid
  // ---------------------------
  {
    id: 'animal-messenger',
    level: 2,
    school: 'enchantment',
    ritual: true,
    concentration: false,
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: '24 hours',
    classes: ['bard', 'druid', 'ranger'],
  },
  {
    id: 'barkskin',
    level: 2,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 1 hour',
    classes: ['druid', 'ranger'],
  },
  {
    id: 'beast-sense',
    level: 2,
    school: 'divination',
    ritual: true,
    concentration: true,
    castingTime: '1 action',
    range: 'Touch',
    components: 'S',
    duration: 'Up to 1 hour',
    classes: ['druid', 'ranger'],
  },
  {
    id: 'darkvision',
    level: 2,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '8 hours',
    classes: ['druid', 'ranger', 'sorcerer', 'wizard'],
  },
  {
    id: 'enhance-ability',
    level: 2,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 1 hour',
    classes: ['bard', 'cleric', 'druid', 'ranger', 'sorcerer'],
  },
  {
    id: 'find-traps',
    level: 2,
    school: 'divination',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['cleric', 'druid', 'ranger'],
  },
  {
    id: 'flame-blade',
    level: 2,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: '1 bonus action',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 10 minutes',
    classes: ['druid'],
  },
  {
    id: 'flaming-sphere',
    level: 2,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute',
    classes: ['druid', 'wizard'],
  },
  {
    id: 'gust-of-wind',
    level: 2,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: 'Self (60-foot line)',
    components: 'V, S, M',
    duration: 'Up to 1 minute',
    classes: ['druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'heat-metal',
    level: 2,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute',
    classes: ['bard', 'druid'],
  },
  {
    id: 'hold-person',
    level: 2,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute',
    classes: ['bard', 'cleric', 'druid', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'lesser-restoration',
    level: 2,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger'],
  },
  {
    id: 'locate-animals-or-plants',
    level: 2,
    school: 'divination',
    ritual: true,
    concentration: false,
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Instantaneous',
    classes: ['bard', 'druid', 'ranger'],
  },
  {
    id: 'locate-object',
    level: 2,
    school: 'divination',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 10 minutes',
    classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'wizard'],
  },
  {
    id: 'moonbeam',
    level: 2,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute',
    classes: ['druid'],
  },
  {
    id: 'pass-without-trace',
    level: 2,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 1 hour',
    classes: ['druid', 'ranger'],
  },
  {
    id: 'protection-from-poison',
    level: 2,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: '1 hour',
    classes: ['cleric', 'druid', 'paladin', 'ranger'],
  },
  {
    id: 'spike-growth',
    level: 2,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, S, M',
    duration: 'Up to 10 minutes',
    classes: ['druid', 'ranger'],
  },
  // ---------------------------
  // Level 3 — Druid
  // ---------------------------
  {
    id: 'call-lightning',
    level: 3,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Up to 10 minutes',
    classes: ['druid'],
  },
  {
    id: 'conjure-animals',
    level: 3,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Up to 1 hour',
    classes: ['druid', 'ranger'],
  },
  {
    id: 'daylight',
    level: 3,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: '1 hour',
    classes: ['cleric', 'druid', 'paladin', 'ranger', 'sorcerer'],
  },
  {
    id: 'dispel-magic',
    level: 3,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['bard', 'cleric', 'druid', 'paladin', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'erupting-earth',
    level: 3,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    classes: ['druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'feign-death',
    level: 3,
    school: 'necromancy',
    ritual: true,
    concentration: false,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 hour',
    classes: ['bard', 'cleric', 'druid', 'wizard'],
  },
  {
    id: 'meld-into-stone',
    level: 3,
    school: 'transmutation',
    ritual: true,
    concentration: false,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: '8 hours',
    classes: ['cleric', 'druid'],
  },
  {
    id: 'plant-growth',
    level: 3,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 action or 8 hours',
    range: '150 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['bard', 'druid', 'ranger'],
  },
  {
    id: 'protection-from-energy',
    level: 3,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Up to 1 hour',
    classes: ['cleric', 'druid', 'ranger', 'sorcerer', 'wizard'],
  },
  {
    id: 'sleet-storm',
    level: 3,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute',
    classes: ['druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'speak-with-plants',
    level: 3,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: 'Self (30-foot radius)',
    components: 'V, S',
    duration: '10 minutes',
    classes: ['bard', 'druid', 'ranger'],
  },
  {
    id: 'water-breathing',
    level: 3,
    school: 'transmutation',
    ritual: true,
    concentration: false,
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: '24 hours',
    classes: ['druid', 'ranger', 'sorcerer', 'wizard'],
  },
  {
    id: 'water-walk',
    level: 3,
    school: 'transmutation',
    ritual: true,
    concentration: false,
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: '1 hour',
    classes: ['cleric', 'druid', 'ranger', 'sorcerer'],
  },
  {
    id: 'wind-wall',
    level: 3,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute',
    classes: ['druid', 'ranger'],
  },
  // ---------------------------
  // Level 4 — Druid
  // ---------------------------
  {
    id: 'blight',
    level: 4,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['druid', 'sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'confusion',
    level: 4,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '90 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute',
    classes: ['bard', 'druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'conjure-minor-elementals',
    level: 4,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 minute',
    range: '90 feet',
    components: 'V, S',
    duration: 'Up to 1 hour',
    classes: ['druid', 'wizard'],
  },
  {
    id: 'conjure-woodland-beings',
    level: 4,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 hour',
    classes: ['druid', 'ranger'],
  },
  {
    id: 'control-water',
    level: 4,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '300 feet',
    components: 'V, S, M',
    duration: 'Up to 10 minutes',
    classes: ['cleric', 'druid', 'wizard'],
  },
  {
    id: 'dominate-beast',
    level: 4,
    school: 'enchantment',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Up to 1 minute',
    classes: ['druid', 'sorcerer'],
  },
  {
    id: 'freedom-of-movement',
    level: 4,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: '1 hour',
    classes: ['bard', 'cleric', 'druid', 'ranger'],
  },
  {
    id: 'giant-insect',
    level: 4,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: 'Up to 10 minutes',
    classes: ['druid'],
  },
  {
    id: 'grasping-vine',
    level: 4,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 bonus action',
    range: '30 feet',
    components: 'V, S',
    duration: 'Up to 1 minute',
    classes: ['druid', 'ranger'],
  },
  {
    id: 'hallucinatory-terrain',
    level: 4,
    school: 'illusion',
    ritual: false,
    concentration: false,
    castingTime: '10 minutes',
    range: '300 feet',
    components: 'V, S, M',
    duration: '24 hours',
    classes: ['bard', 'druid', 'warlock', 'wizard'],
  },
  {
    id: 'ice-storm',
    level: 4,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: '300 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    classes: ['cleric', 'druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'locate-creature',
    level: 4,
    school: 'divination',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 1 hour',
    classes: ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'wizard'],
  },
  {
    id: 'polymorph',
    level: 4,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 hour',
    classes: ['bard', 'druid', 'sorcerer', 'wizard'],
  },
  {
    id: 'stone-shape',
    level: 4,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    classes: ['cleric', 'druid', 'wizard'],
  },
  {
    id: 'stoneskin',
    level: 4,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 1 hour',
    classes: ['druid', 'ranger', 'sorcerer', 'wizard'],
  },
  {
    id: 'wall-of-fire',
    level: 4,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute',
    classes: ['druid', 'sorcerer', 'wizard'],
  },
  // ---------------------------
  // Level 5 — Druid
  // ---------------------------
  {
    id: 'antilife-shell',
    level: 5,
    school: 'abjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: 'Self (10-foot radius)',
    components: 'V, S',
    duration: 'Up to 1 hour',
    classes: ['druid'],
  },
  {
    id: 'awaken',
    level: 5,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '8 hours',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    classes: ['bard', 'druid'],
  },
  {
    id: 'commune-with-nature',
    level: 5,
    school: 'divination',
    ritual: true,
    concentration: false,
    castingTime: '1 minute',
    range: 'Self',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['druid', 'ranger'],
  },
  {
    id: 'conjure-elemental',
    level: 5,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 minute',
    range: '90 feet',
    components: 'V, S, M',
    duration: 'Up to 1 hour',
    classes: ['druid', 'wizard'],
  },
  {
    id: 'contagion',
    level: 5,
    school: 'necromancy',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: '7 days',
    classes: ['cleric', 'druid'],
  },
  {
    id: 'geas',
    level: 5,
    school: 'enchantment',
    ritual: false,
    concentration: false,
    castingTime: '1 minute',
    range: '60 feet',
    components: 'V',
    duration: '30 days',
    classes: ['bard', 'cleric', 'druid', 'paladin', 'wizard'],
  },
  {
    id: 'greater-restoration',
    level: 5,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    classes: ['bard', 'cleric', 'druid'],
  },
  {
    id: 'insect-plague',
    level: 5,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '300 feet',
    components: 'V, S, M',
    duration: 'Up to 10 minutes',
    classes: ['cleric', 'druid', 'sorcerer'],
  },
  {
    id: 'mass-cure-wounds',
    level: 5,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['bard', 'cleric', 'druid'],
  },
  {
    id: 'planar-binding',
    level: 5,
    school: 'abjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 hour',
    range: '60 feet',
    components: 'V, S, M',
    duration: '24 hours',
    classes: ['bard', 'cleric', 'druid', 'wizard'],
  },
  {
    id: 'reincarnate',
    level: 5,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 hour',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Instantaneous',
    classes: ['druid'],
  },
  {
    id: 'scrying',
    level: 5,
    school: 'divination',
    ritual: false,
    concentration: true,
    castingTime: '10 minutes',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Up to 10 minutes',
    classes: ['bard', 'cleric', 'druid', 'warlock', 'wizard'],
  },
  {
    id: 'tree-stride',
    level: 5,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: 'Up to 1 minute',
    classes: ['druid', 'ranger'],
  },
  {
    id: 'wall-of-stone',
    level: 5,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 10 minutes',
    classes: ['druid', 'sorcerer', 'wizard'],
  },
  // ---------------------------
  // Cross-class spells used in Land terrain lists (classes does NOT include 'druid')
  // ---------------------------
  // Coast terrain spells
  {
    id: 'mirror-image',
    level: 2,
    school: 'illusion',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: '1 minute',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'misty-step',
    level: 2,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 bonus action',
    range: 'Self',
    components: 'V',
    duration: 'Instantaneous',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  // water-breathing already included (druid list)
  // water-walk already included (druid list)
  // freedom-of-movement already included (druid list)
  // Desert terrain spells
  {
    id: 'blur',
    level: 2,
    school: 'illusion',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: 'Self',
    components: 'V',
    duration: 'Up to 1 minute',
    classes: ['sorcerer', 'wizard'],
  },
  {
    id: 'silence',
    level: 2,
    school: 'illusion',
    ritual: true,
    concentration: true,
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Up to 10 minutes',
    classes: ['bard', 'cleric', 'ranger'],
  },
  {
    id: 'create-food-and-water',
    level: 3,
    school: 'conjuration',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['cleric', 'paladin'],
  },
  // protection-from-energy already in druid list
  // hallucinatory-terrain already in druid list
  // blight already in druid list
  // Forest terrain spells
  {
    id: 'spider-climb',
    level: 2,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 1 hour',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'divination',
    level: 4,
    school: 'divination',
    ritual: true,
    concentration: false,
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S, M',
    duration: 'Instantaneous',
    classes: ['cleric', 'druid'],
  },
  // Grassland terrain spells
  {
    id: 'invisibility',
    level: 2,
    school: 'illusion',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 1 hour',
    classes: ['bard', 'sorcerer', 'warlock', 'wizard'],
  },
  // daylight already in druid list
  {
    id: 'haste',
    level: 3,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute',
    classes: ['sorcerer', 'wizard'],
  },
  // Mountain terrain spells
  {
    id: 'lightning-bolt',
    level: 3,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: 'Self (100-foot line)',
    components: 'V, S, M',
    duration: 'Instantaneous',
    classes: ['sorcerer', 'wizard'],
  },
  // meld-into-stone already in druid list
  // stone-shape already in druid list
  // stoneskin already in druid list
  // Swamp terrain spells
  {
    id: 'acid-arrow',
    level: 2,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: '90 feet',
    components: 'V, S, M',
    duration: 'Instantaneous',
    classes: ['wizard'],
  },
  {
    id: 'darkness',
    level: 2,
    school: 'evocation',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, M',
    duration: 'Up to 10 minutes',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'stinking-cloud',
    level: 3,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '90 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  // insect-plague already in druid list
  // Underdark terrain spells
  {
    id: 'web',
    level: 2,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M',
    duration: 'Up to 1 hour',
    classes: ['sorcerer', 'wizard'],
  },
  {
    id: 'gaseous-form',
    level: 3,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M',
    duration: 'Up to 1 hour',
    classes: ['sorcerer', 'warlock', 'wizard'],
  },
  {
    id: 'greater-invisibility',
    level: 4,
    school: 'illusion',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Up to 1 minute',
    classes: ['bard', 'sorcerer', 'wizard'],
  },
  {
    id: 'cloudkill',
    level: 5,
    school: 'conjuration',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Up to 10 minutes',
    classes: ['sorcerer', 'wizard'],
  },
  // Mountain level 9 terrain spell
  {
    id: 'passwall',
    level: 5,
    school: 'transmutation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S, M',
    duration: '1 hour',
    classes: ['wizard'],
  },
  // Grassland level 9 terrain spell
  {
    id: 'dream',
    level: 5,
    school: 'illusion',
    ritual: false,
    concentration: false,
    castingTime: '1 minute',
    range: 'Special',
    components: 'V, S, M',
    duration: '8 hours',
    classes: ['bard', 'warlock', 'wizard'],
  },
  // Arctic terrain spells
  {
    id: 'slow',
    level: 3,
    school: 'transmutation',
    ritual: false,
    concentration: true,
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S, M',
    duration: 'Up to 1 minute',
    classes: ['sorcerer', 'wizard'],
  },
  {
    id: 'cone-of-cold',
    level: 5,
    school: 'evocation',
    ritual: false,
    concentration: false,
    castingTime: '1 action',
    range: 'Self (60-foot cone)',
    components: 'V, S, M',
    duration: 'Instantaneous',
    classes: ['sorcerer', 'wizard'],
  },
];

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

const SPELL_MAP: ReadonlyMap<string, SpellDef> = new Map(SPELL_CATALOG.map((s) => [s.id, s]));

export function getSpellDef(id: string): SpellDef | undefined {
  return SPELL_MAP.get(id);
}

/** Fail-fast lookup for trusted source data. Throws when the spell id is not in the catalog. */
export function requireSpellDef(id: string): SpellDef {
  const def = SPELL_MAP.get(id);
  if (def === undefined) {
    throw new Error(`Unknown spell id: "${id}". Check source data or catalog.`);
  }
  return def;
}

/**
 * Returns all spells in the catalog for a given class and optional level filter.
 * When level is omitted, returns all spells for the class across all levels.
 */
/**
 * All spell IDs present in gamedata.json — derived from the JSON type so
 * that i18next key-checking can resolve `spells.<id>.name` exactly.
 */
export type SpellId = keyof typeof gamedata.spells;

/** A typed gamedata key for a spell name: `spells.<id>.name` */
export type SpellNameKey = `spells.${SpellId}.name`;
/** A typed gamedata key for a spell description: `spells.<id>.description` */
export type SpellDescriptionKey = `spells.${SpellId}.description`;

/**
 * Returns the typed gamedata key for a spell's name.
 * `spellId` must be a known SpellId from the catalog. Cast from `string` only
 * when the id is guaranteed to come from the catalog (e.g., SPELL_CATALOG entries
 * or LAND_TERRAIN_SPELL_GRANTS).
 */
export function getSpellNameKey(spellId: SpellId): SpellNameKey {
  return `spells.${spellId}.name`;
}

/**
 * Returns the typed gamedata key for a spell's description.
 * Same narrowing requirement as getSpellNameKey.
 */
export function getSpellDescriptionKey(spellId: SpellId): SpellDescriptionKey {
  return `spells.${spellId}.description`;
}

export function getSpellsForList(classId: ClassId, level?: SpellLevel): readonly SpellDef[] {
  return SPELL_CATALOG.filter((s) => {
    if (!s.classes.includes(classId)) return false;
    if (level !== undefined && s.level !== level) return false;
    return true;
  });
}

// Log a warning at module load if any duplicate ids are detected (development guard)
(function detectDuplicateIds() {
  const seen = new Set<string>();
  for (const spell of SPELL_CATALOG) {
    if (seen.has(spell.id)) {
      logger.warn(`Duplicate spell id detected in SPELL_CATALOG: "${spell.id}"`);
    }
    seen.add(spell.id);
  }
})();
